### ISSUE TITLE
下载地址的问题

### ISSUE THREAD

**Issue by Hello-XPH** [lxxlxx888/Reer#3]
下载地址干嘛放在百度网盘，放在github不行吗？

**Comment by catofmrlu** [comment]
不是下载地址，是软件存储在百度云盘，分享链接一直被封，所以没法贴出来

**Comment by Hello-XPH** [comment]
难受了

**Comment by Hello-XPH** [comment]
干嘛不放在github，看别人都是把软件放在github的。
![image](https://user-images.githubusercontent.com/56664327/85081319-38bde500-b1fe-11ea-9160-88cc5f0187e1.png)主要在百度网盘下载麻烦

**Comment by Hello-XPH** [comment]
作者弄一下，行吗？

**Comment by catofmrlu** [comment]
兄弟，他们只是一个app的不同版本。游戏很大的，而且很多。

**Comment by Hello-XPH** [comment]
我知道
明白了
